@startuml Diagrama_de_estados

[*] --> SinAcceso 

SinAcceso --> InicioDeSesion
SinAcceso --> Registro
Registro --> InicioDeSesion
InicioDeSesion --> AccesoContenidos
AccesoContenidos --> [*]


@enduml